### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by behrmann** [exviva/stew#1]
I just found your beautiful app, and I wanted to look to put it in the [submission queue ](https://f-droid.org/forums/forum/submission-queue) (for which I still have to look whether all your dependencies are FOSS), but it would be of great help if you could add tags to your releases. Thanks a lot for the app!

**Comment by exviva** [comment]
I'm glad you like it :).

I've pushed the tags for releases

**Comment by exviva** [comment]
I assume you meant git tags? :)

**Comment by behrmann** [comment]
Yep, that's what I meant. Thanks! :)
