### ISSUE TITLE
Text part of post missing

### ISSUE THREAD

**Issue by behrmann** [exviva/stew#3]
Looking through my soup yesterday, I noticed that the text part, below images is missing. That is a pretty big problem. It should preferably be shown in the normal flow of posts.

**Comment by exviva** [comment]
Could you upload a screenshot from the website, and from the app?

**Comment by behrmann** [comment]
Sure.
![untitled](https://cloud.githubusercontent.com/assets/1044766/9011270/72e3827a-37ac-11e5-9cd6-ebf18eb532cf.png)
![screenshot_2015-07-31-17-43-25](https://cloud.githubusercontent.com/assets/1044766/9011277/88e48f42-37ac-11e5-986b-86ab8d926468.png)

**Comment by behrmann** [comment]
Ok, there a bit big, but I have no clue how to scale them here on Github. Except for the problem that all images are shown somewhat zoomed (showing them full as default would be nicer, too), you see that the text (the blue link) that is below the Fry picture in the upper image is not shown in the lower one.

**Comment by exviva** [comment]
Ah, now I see what you mean. Supporting different post types and mixed content is already on my list, thanks for your input!

**Comment by exviva** [comment]
Simple way of showing post text underneath image released in 0.3.0.
