### ISSUE TITLE
"Friends" and "Friends of Friends" not updating

### ISSUE THREAD

**Issue by behrmann** [exviva/stew#4]
I just noticed that my "Friends" and "Friends of Friends" are not loading, the loading text is shortly shown on the bottom the screen, but no posts are loaded and the screen remains white. "My soup" updates correctly though. Logging out and back in solves the problem.

**Comment by exviva** [comment]
Yeah, I'm having the same problem, probably has to do with cookie expiration. I'll look into it on the weekend.

**Comment by exviva** [comment]
Fixed in 0.2.0
